[package]
name = "rust-cli-task-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.41"
colored = "3.0.0"
